getTeam API 페이지네이션 부분 개선 및 !조건문 구체화
Matching42/Matching42-back pull request #128
Opened 2021-07-27 05:46 UTC by atimangel

resolved:#127

조건식에 !들어간 부분 === undefined || === null 로 변경

for push로 특정 범위의 배열을 만들었는데 slice메소드 사용

page랑 limit 쿼리에 값을 넣어서 보냈는지 체크하고 아무 것도 안넣어서 보냈다면 allTeams를 반환하고 그 이후에 
페이지네이션을 한 후 반환했다.
이렇게 하면 반환을 두 번 하게 돼서 retrun 을 써줘야한다.
반환을 한 번 하도록 하는게 나을 것 같아서 page랑 limit중 값이 있는게 있다면 특정 범위의 배열을 새로 allTeams에 할당했다.
새로운 배열을 만들 필요가 없을 것 같아서 pageTeams는 제거하고 allTeams에 재할당했다.

2021-07-27 10:19 UTC, hokim2407 requested changes

2021-07-27 10:19 UTC, hokim2407 commented on srcs/controllers/controller.getTeam.tsx
> +                req.query.page !== undefined ||
이 부분 조건들 && 여야 할 것 같습니다.

2021-07-27 12:45 UTC, Lks9172 requested changes

2021-07-27 12:45 UTC, Lks9172 commented on srcs/controllers/controller.getTeam.tsx
> +                req.query.page !== undefined ||
그렇네요 조건이 다르네요

2021-07-28 03:19 UTC, hminn approved these changes

2021-07-28 03:20 UTC, hokim2407 submitted a review, later dismissed

2021-07-28 04:11 UTC, Lks9172 submitted a review, later dismissed

2021-07-28 07:34 UTC, hminn approved these changes

2021-07-28 07:34 UTC, Lks9172 approved these changes

2021-07-28 08:52 UTC, hokim2407 approved these changes

2021-07-28 09:37 UTC, merged